### ISSUE TITLE
Adding Fallback if Translation Missing

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Neos.Logs#12]
If you use a German Backend for example, the Module is named `Shel.Neos.Logs:Main:module.label`
It would be nicer to have the english translation there.

**Comment by Sebobo** [comment]
Works on my machine ;)

Did you change the Flow default locale without a fallback order?

**Comment by paavo** [comment]
my fault 🤦 
didn't knew about the fallback order 😆 

```
Neos:
  Flow:
    i18n:
      defaultLocale: de
      fallbackRule:
        order: ['en']
```
